#!/bin/bash

# Unofficial bash strict mode http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -eu
set -o pipefail
IFS=$'\n\t'

SENDGRID_USERNAME=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.sendgrid_username --with-decryption --query "Parameter.Value" --out text)
SENDGRID_PASSWORD=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.sendgrid_password --with-decryption --query "Parameter.Value" --out text)
EMAIL_FROM=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.email_from --with-decryption --query "Parameter.Value" --out text)
EMAIL_TO=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.email_to --with-decryption --query "Parameter.Value" --out text)
NEWSGROUPDIRECT_USERNAME=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.newsgroupdirect_username --with-decryption --query "Parameter.Value" --out text)
NEWSGROUPDIRECT_PASSWORD=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.newsgroupdirect_password --with-decryption --query "Parameter.Value" --out text)
NZB_KEY=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.nzb_key --with-decryption --query "Parameter.Value" --out text)
OZNZB_API_KEY=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.oznzb_api_key --with-decryption --query "Parameter.Value" --out text)
USENETFARM_USERNAME=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.usenetfarm_username --with-decryption --query "Parameter.Value" --out text)
USENETFARM_PASSWORD=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.usenetfarm_password --with-decryption --query "Parameter.Value" --out text)
PLEX_TOKEN=$(aws ssm get-parameter --region eu-west-1 --name plex.token --with-decryption --query "Parameter.Value" --out text)
COUCHPOTATO_API_KEY=$(aws ssm get-parameter --region eu-west-1 --name couchpotato.api_key --with-decryption --query "Parameter.Value" --out text)
SABNZBD_API_KEY=$(aws ssm get-parameter --region eu-west-1 --name sabnzbd.api_key --with-decryption --query "Parameter.Value" --out text)

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_REGION

cat /app/sabnzbd.ini \
  | sed "s|SABNZBD_API_KEY|$SABNZBD_API_KEY|" \
  | sed "s|EMAIL_FROM|$EMAIL_FROM|" \
  | sed "s|EMAIL_TO|$EMAIL_TO|" \
  | sed "s|EMAIL_ACCOUNT|$SENDGRID_USERNAME|" \
  | sed "s|EMAIL_PASSWORD|$SENDGRID_PASSWORD|" \
  | sed "s|NEWSGROUPDIRECT_PASSWORD|$NEWSGROUPDIRECT_PASSWORD|" \
  | sed "s|NEWSGROUPDIRECT_USERNAME|$NEWSGROUPDIRECT_USERNAME|" \
  | sed "s|USENETFARM_PASSWORD|$USENETFARM_PASSWORD|" \
  | sed "s|USENETFARM_USERNAME|$USENETFARM_USERNAME|" \
  | sed "s|NZB_KEY|$NZB_KEY|" \
  | sed "s|OZNZB_API_KEY|$OZNZB_API_KEY|" \
  > /tmp/sabnzbd.ini

cat /app/autoProcessMedia.cfg \
  | sed "s/SABNZBD_API_KEY/$SABNZBD_API_KEY/" \
  | sed "s/COUCHPOTATO_API_KEY/$COUCHPOTATO_API_KEY/" \
  | sed "s/PLEX_TOKEN/$PLEX_TOKEN/" \
  > /opt/nzbToMedia/autoProcessMedia.cfg

exec ${*:1}
